# Based on https://github.com/hvr/multi-ghc-travis
language: c

sudo: false

env:
 - CABALVER=1.18 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=head GHCVER=head

addons:
  apt:
    sources:
     - hvr-ghc
    packages:
     - cabal-install-1.22
     - ghc-7.8.4
     - cabal-install-1.18
     - ghc-7.10.1
     - cabal-install-head
     - ghc-head

matrix:
  allow_failures:
   - env: CABALVER=head GHCVER=head

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests

script:
 - cabal configure --enable-tests -v2
 - cabal build
 - cabal test --show-details=always
 - cabal check
 - cabal sdist
 - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
